YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "AnimationLoopType",
        "AnimationTypes",
        "AudioManager",
        "CircularDistortionEffect",
        "Colors",
        "CommandFieldFlags",
        "Component",
        "Component_ActionHandler",
        "Component_Animation",
        "Component_AnimationExecutor",
        "Component_AnimationHandler",
        "Component_Animator",
        "Component_BindingHandler",
        "Component_BlendAnimation",
        "Component_BlurAnimation",
        "Component_CallSceneInterpreter",
        "Component_CharacterBehavior",
        "Component_CommandInterpreter",
        "Component_CommonEventBehavior",
        "Component_Container",
        "Component_DataGridBehavior",
        "Component_DomainContainer",
        "Component_Draggable",
        "Component_EventEmitter",
        "Component_FieldAnimation",
        "Component_Frame",
        "Component_FrameAnimation",
        "Component_FreeLayoutBehavior",
        "Component_GameSceneBehavior",
        "Component_GridLayoutBehavior",
        "Component_Handler",
        "Component_HotspotBehavior",
        "Component_ImageAnimation",
        "Component_ImageMap",
        "Component_InputHandler",
        "Component_IntervalTimer",
        "Component_LayoutBehavior",
        "Component_LayoutSceneBehavior",
        "Component_Live2D",
        "Component_Live2DAnimation",
        "Component_MaskAnimation",
        "Component_MessageBehavior",
        "Component_MessageTextRenderer",
        "Component_MoveAnimation",
        "Component_NumberInput",
        "Component_PanelBehavior",
        "Component_PathAnimation",
        "Component_PixelateAnimation",
        "Component_Quad",
        "Component_RotateAnimation",
        "Component_SceneBehavior",
        "Component_ShakeAnimation",
        "Component_SpreadLayoutBehavior",
        "Component_Sprite",
        "Component_StackLayoutBehavior",
        "Component_TextBehavior",
        "Component_TextInput",
        "Component_TextRenderer",
        "Component_ThreePartImage",
        "Component_TilingPlane",
        "Component_TilingSprite",
        "Component_Timer",
        "Component_TintAnimation",
        "Component_UIBehavior",
        "Component_Viewport",
        "Component_Visual",
        "Component_WebStartBehavior",
        "Component_WobbleAnimation",
        "Component_ZoomAnimation",
        "ContainerDisposeBehavior",
        "DataManager",
        "DataOptimizer",
        "Easing",
        "EasingTypes",
        "Easings",
        "Fonts",
        "Formula",
        "GameManager",
        "GameTemp",
        "Helper",
        "ImageHandling",
        "InterpreterContext",
        "LanguageManager",
        "LayoutManagementMode",
        "LivePreviewInfo",
        "Main",
        "MessageSettings",
        "ObjectManager",
        "Object_Animation",
        "Object_Background",
        "Object_Base",
        "Object_Character",
        "Object_CommonEvent",
        "Object_Container",
        "Object_DataGrid",
        "Object_DomainContainer",
        "Object_Frame",
        "Object_FreeLayout",
        "Object_GridLayout",
        "Object_Hotspot",
        "Object_Image",
        "Object_ImageMap",
        "Object_IntervalTimer",
        "Object_Layout",
        "Object_Live2DCharacter",
        "Object_Message",
        "Object_MessageArea",
        "Object_Panel",
        "Object_Picture",
        "Object_Scene",
        "Object_SpreadLayout",
        "Object_StackLayout",
        "Object_Text",
        "Object_ThreePartImage",
        "Object_Timer",
        "Object_UIElement",
        "Object_Video",
        "Object_Viewport",
        "Object_Visual",
        "RecordManager",
        "RendererTextLine",
        "RendererToken",
        "ResourceLoader",
        "ResourceManager",
        "SceneManager",
        "Space",
        "Sprite_Debug",
        "Style",
        "UIElementPoint",
        "UIElementRectangle",
        "UIManager",
        "UpdateBehavior",
        "VariableStore"
    ],
    "modules": [
        "gs",
        "gs.RendererTextLine",
        "ui",
        "vn"
    ],
    "allModules": [
        {
            "displayName": "gs",
            "name": "gs",
            "description": "<p>A storage for different kind of game variables. The following scopes\nfor variables exist:</p>\n\n- Local Variables -> Only valid for the current scene.\n- Global Variables -> Valid for the whole game but bound to a single save-game.\n- Persistent Variables -> Valid for the whole game indepentent from the save-games.\n\n<p>The following data-types exist:</p>\n- Strings -> Variables storing text data.\n- Numbers -> Variables storing integer number values.\n- Booleans -> Variables storing boolean values. (Called \"Switches\" for easier understanding)\n- Lists -> Variables storing multiple other variables. Lists can also contain Lists.\n<p>\nLocal variables are stored by scene UID. For each scene UID a list of local variables is stored.</p>\n\n<p>Global and persistent variables are stored and a specific domain. A domain is just a unique name such\nas <i>com.example.game</i> for example. The default domain is an empty string. Domains are useful to avoid\noverlapping of variable numbers when sharing content with other users. </p>"
        },
        {
            "displayName": "gs.RendererTextLine",
            "name": "gs.RendererTextLine",
            "description": "Stores a text line."
        },
        {
            "displayName": "ui",
            "name": "ui",
            "description": "An ui point is like a regular point with an x- and y-coordinate but if one of the\ncoordinates is changed the <b>needsUpdate</b> property of the\nassigned game object will be set to <b>true</b> to trigger a refresh."
        },
        {
            "displayName": "vn",
            "name": "vn",
            "description": "A scene object manages a whole visual novel scene with backgrounds, characters,\nmessages, etc."
        }
    ],
    "elements": []
} };
});