YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "ActionDescriptor",
        "AnimationDescriptor",
        "BindingDescriptor",
        "BindingRatioConversionDescriptor",
        "BlendToPrimitiveAnimationDescriptor",
        "ChangeImagesPrimitiveAnimationDescriptor",
        "ChangeToPrimitiveAnimationDescriptor",
        "ComponentDescriptor",
        "ConditionDescriptor",
        "DraggableDescriptor",
        "EventDescriptor",
        "FontDescriptor",
        "FontOutlineDescriptor",
        "ImageMapHotspotDescriptor",
        "MaskToPrimitiveAnimationDescriptor",
        "MoveToPrimitiveAnimationDescriptor",
        "PlayAnimationPrimitiveAnimationDescriptor",
        "PrimitiveAnimationDescriptor",
        "SoundPrimitiveAnimationDescriptor",
        "WaitPrimitiveAnimationDescriptor",
        "ZoomToPrimitiveAnimationDescriptor",
        "ui.Control",
        "ui.Frame",
        "ui.FreeLayout",
        "ui.GridLayout",
        "ui.Image",
        "ui.ImageButton",
        "ui.ImageMap",
        "ui.Layout",
        "ui.Message",
        "ui.Panel",
        "ui.SpreadLayout",
        "ui.StackLayout",
        "ui.Text",
        "ui.ThreePartImage",
        "ui.Video"
    ],
    "modules": [],
    "allModules": [],
    "elements": []
} };
});