YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "DataRecordView",
        "DataSourceDescriptor",
        "DialogDescriptor",
        "FormatHelper",
        "GS.GAME",
        "GSButton",
        "GSCheckBox",
        "GSCollectionView",
        "GSColorView",
        "GSContainer",
        "GSDataRecordField",
        "GSDispositionView",
        "GSDocumentTree",
        "GSFilePathBox",
        "GSGraphicalPathView",
        "GSImageView",
        "GSLabel",
        "GSLive2DView",
        "GSParameterView",
        "GSPopupField",
        "GSQCheckBox",
        "GSQDataRecordField",
        "GSQItem",
        "GSQPopupField",
        "GSQSlider",
        "GSQStepper",
        "GSQTextArea",
        "GSRadioButton",
        "GSResourcePopupField",
        "GSSceneContentView",
        "GSSceneToolBox",
        "GSSlider",
        "GSSpacer",
        "GSSplitView",
        "GSStepper",
        "GSTabView",
        "GSTable",
        "GSTextField",
        "GSToneView",
        "GSViewItem",
        "LanguageBundle",
        "SceneCommand",
        "View"
    ],
    "modules": [],
    "allModules": [],
    "elements": []
} };
});