YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "gs.Application",
        "gs.Audio",
        "gs.AudioBuffer",
        "gs.AudioBufferReference",
        "gs.Bitmap",
        "gs.BlendMode",
        "gs.BlurEffect",
        "gs.Color",
        "gs.Data",
        "gs.Effect",
        "gs.EffectCollection",
        "gs.EffectInfo",
        "gs.Font",
        "gs.Frame",
        "gs.GameStorage",
        "gs.GameStorageLocations",
        "gs.GraphicEffect",
        "gs.GraphicEffectType",
        "gs.GraphicObject",
        "gs.Graphics",
        "gs.Input",
        "gs.Live2DModel",
        "gs.Live2DMotionManager",
        "gs.Live2DMotionPlayTypes",
        "gs.Live2DObject",
        "gs.Mask",
        "gs.MaskingType",
        "gs.MotionBlur",
        "gs.MouseInput",
        "gs.PixelateEffect",
        "gs.Point",
        "gs.Quad",
        "gs.Rect",
        "gs.RenderTask",
        "gs.Renderer",
        "gs.Sprite",
        "gs.Texture2D",
        "gs.TextureFilter",
        "gs.ThreePartImage",
        "gs.Tilemap",
        "gs.TilemapLayer",
        "gs.TilemapRenderInfo",
        "gs.TilesetConfiguration",
        "gs.TilingSprite",
        "gs.Tone",
        "gs.Video",
        "gs.Viewport",
        "gs.WobbleEffect"
    ],
    "modules": [],
    "allModules": [],
    "elements": []
} };
});